### ISSUE TITLE
minimize size of editor background

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#100]
Remove blue area https://github.com/microsoft/microcode/commit/d8b1bac3000a486e9f1a70061c5840177f197c6a#diff-be010b1c9291053eec50f967679bbb532446029563df6d51a41e3ee9ea7246d7R109

**Comment by tballmsft** [comment]
Not really clear what you want. change the background color?

**Comment by eanders-ms** [comment]
I have a local fix for this. The editor background image doesn't need to be full 160x120.

**Comment by tballmsft** [comment]
@eanders-ms - is this in?

**Comment by eanders-ms** [comment]
yep
