### ISSUE TITLE
loud and speaker icons are the same

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#116]
different icons plz

**Comment by tballmsft** [comment]
I don't see the problem here - the loud icon is under microphone. Maybe removed sound waves from speaker icon???  Or put sound emoji next to it?

**Comment by pelikhan** [comment]
We should have unique icons. See screenshot below.

![image](https://user-images.githubusercontent.com/4175913/191397122-7edf2047-6335-434c-bd6b-62599336c387.jpeg)

**Comment by tballmsft** [comment]
yes, but context matters, maybe turn the speaker for "loud" so it faces the microphone? That is, flip it!

**Comment by pelikhan** [comment]
It's easier if each icon is globally unique, no context needed, imo.
________________________________

**Comment by clkantner** [comment]
I made a separate icon for the sound emoji so closing this out
