### ISSUE TITLE
Chain multiple actions

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#129]
Ability to chain more than one actuator in a rule. Like paint, sound, paint...

**Comment by tballmsft** [comment]
two basic options here
- linear chaining (easiest, but then a lot of scrolling)
- nested do sections (needs some UI to insert a second action), so a rule is like an "if (e) then { D1; D2, D3 }

I like the second option as you'll be able to see that a single has multiple (parallel actions)

**Comment by pelikhan** [comment]
Either way, you'll scroll. Iet's punt this for now, it does add complexity and maybe we don't need it.
