### ISSUE TITLE
random number generator

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#13]
An example of a parameterized sensor is a random number generation that gives a number between 1 and N, for N \in {3,4,5,6}.  

For example, in rock-paper-scissors, we need to get a random number in {1,2,3}

A related issue is that we need to branch on that random number in three separate rules.

How can we do this in the current editor scheme?

**Comment by tballmsft** [comment]
Maybe the solution to the above is to assign a randomly generated number to a variable (using an acuator and modifer) and then have a rule that "senses" change to the variable. Essentially, break into lower-level steps.  Seems tricky though.

**Comment by tballmsft** [comment]
@eanders-ms - any thoughts on generating a random number - is this a sensor or actuator that raises a signal? I think the latter.

**Comment by pelikhan** [comment]
done
