### ISSUE TITLE
dialogs need a chrome

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#132]
We would be nice to have a chrome around dialog. it's very tight right now.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/4175913/191567726-aaceedf2-ae5c-418b-a0cd-d01b3f652f5d.png">

**Comment by clkantner** [comment]
@pelikhan what exactly do you mean by chrome? Like outline? That's what I was thinking. And you you mean around the text or the black box behind the icons?

**Comment by clkantner** [comment]
Ok just confirmed it's the box behind the icons

**Comment by clkantner** [comment]
Here is how I think we should approach the dialogue box. Just a few simple outlines! See example with and without backdrop below. 
<img width="942" alt="Screen Shot 2022-09-21 at 3 39 13 PM" src="https://user-images.githubusercontent.com/106267801/191622882-dea91bdb-7ec4-4547-8360-52f3827ff7b3.png">

<img width="913" alt="Screen Shot 2022-09-21 at 3 39 34 PM" src="https://user-images.githubusercontent.com/106267801/191622879-aa12448b-2a66-4dab-aa8b-c8b50b3e26d6.png">

**Comment by pelikhan** [comment]
@eanders-ms can we reuse the cursor logic to render around the dialog?

**Comment by pelikhan** [comment]
current redesign has a crhome, closing for now
