### ISSUE TITLE
move pages to right + no carousel

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#135]
- make sure focus is on first rule
- remove carousel

<img width="379" alt="image" src="https://user-images.githubusercontent.com/4175913/191575786-bce8663a-a3d3-4077-a349-62167fa59227.png">

**Comment by mmoskal** [comment]
there is also a bug when you click page number, select a different page, and then keep clicking the page number

**Comment by pelikhan** [comment]
should the page move to the left? less movement on the cursor

**Comment by pelikhan** [comment]
left:
![image](https://user-images.githubusercontent.com/4175913/191817792-5b230866-2f1b-4371-8c3a-327f69f6cd50.png)
right:
![demo](https://user-images.githubusercontent.com/4175913/191818038-e0fcb940-b86f-47db-b41c-6d7b16a9527a.gif)
