### ISSUE TITLE
sample icons shouldn't have a white border

### ISSUE THREAD

**Issue by clkantner** [microsoft/microcode#150]
The sample icons have too big of a border around

<img width="402" alt="Screen Shot 2022-09-22 at 10 11 02 AM" src="https://user-images.githubusercontent.com/106267801/191809969-0d19e0a1-f100-4a44-aac2-4d89006fa8be.png">
<img width="529" alt="Screen Shot 2022-09-22 at 10 10 53 AM" src="https://user-images.githubusercontent.com/106267801/191809985-2b967880-7275-4de4-aa74-7a6084e0be88.png">

**Comment by pelikhan** [comment]
Related to home screen upgrade (https://github.com/microsoft/microcode/issues/115)
