### ISSUE TITLE
add depth to led editor?

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#162]
It's very flat.

![image](https://user-images.githubusercontent.com/4175913/191886656-6c833930-b161-4a29-85b3-cfda68e951a1.png)

**Comment by pelikhan** [comment]
closer to 
![image](https://user-images.githubusercontent.com/4175913/191895279-873e5a70-caaa-4fb7-b5d4-28dd219b5e04.png)
 ?

**Comment by clkantner** [comment]
I'm on it!

**Comment by clkantner** [comment]
<img width="585" alt="Screen Shot 2022-09-23 at 9 41 09 AM" src="https://user-images.githubusercontent.com/106267801/192010507-01831082-e7a9-4b7a-8619-0dea86f69f31.png">

This would be my recommendation. Let me know if you have thoughts or if I should add this to the code

**Comment by eanders-ms** [comment]
Oh nice use of orange. You can add it to the code by editing the (very poorly named) `solid_red` and `solid_black` images in assets.ts.

**Comment by clkantner** [comment]
Adding now. Is there a way to change the background from dark purple to black so it matches our other modals?

**Comment by eanders-ms** [comment]
Minor code change. Do you want all modals to be in this style?

**Comment by clkantner** [comment]
Yes if possible!
