### ISSUE TITLE
scrolling past the bottom led in led editor crashes the editor

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#163]
Keep going and it will crash. Looks like row goes over the array limit

**Comment by oldukhno** [comment]
Could not crash the app, but the LET editor navigation is misbehaving in 3 ways:

Way #1
Steps to reproduce:

1) Open LED editor
2) Move down 3 times

-> Result: You can neither navigate to the right nor to the left anymore
-> Expected result: we should be able to continue navigating to the right and to the left

Way #2
Steps to reproduce:
1) Open editor 
2) Move right 2 times
3) Move up 3 times

-> Result: The cursor did not move to the "thrash bin" tile
-> Expected result: The cursor should move to the "thrash bin" tile

Way #3
Steps to reproduce:
1) Open editor 
2) Move down 2 times
3) Move left 2 times
4) Move down 1 time

-> Result: The cursor selects the "thrash bin" tile. Accessibility reports: "live region: led 0 5 unknown" (meaning that the "thrash bin" tile is not at 0:0 anymore)
-> Expected result: The cursor should stay at the left bottom corner of the LED editor
