### ISSUE TITLE
pipes using A/B/C is confusing in relation to buttons

### ISSUE THREAD

**Issue by jaustin** [microsoft/microcode#176]
The pipes using A/B/(C) overlaps with the buttons. It also makes it less a 'pre-reader interface'
Could we have square, circle, triangle, or similar instead?

**Comment by pelikhan** [comment]
Good point, A,B are already overloaded with button names.

**Comment by tballmsft** [comment]
Will Do.

**Comment by tballmsft** [comment]
See new icons

**Comment by tballmsft** [comment]
The problem is there is very little space.  Maybe can move things around to get more space for icons

**Comment by pelikhan** [comment]
Going back to letters for now.
