### ISSUE TITLE
function calls and pipe sending are confusing in terms of order of operations

### ISSUE THREAD

**Issue by jaustin** [microsoft/microcode#177]
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/147113/192012670-37d2b591-b83c-4669-841f-c0b22604f53f.png">

In the following example, it's not clear whether this bit is saying 
<img width="405" alt="image" src="https://user-images.githubusercontent.com/147113/192012899-f301949a-446d-4aff-8cd6-9d0d0e593306.png">
Is this "roll a die and put 3 in a pipe" or "roll a die (with the argument 3), then put the answer in a pipe"

It feels like in general where arguments are being provided, there needs to be some visual indication. OR, arguments happen inside a dedicated screen (more like the LED pattern chooser)

**Comment by pelikhan** [comment]
The dice with value following as the range is defintely confusing.

**Comment by tballmsft** [comment]
This is a known issue with the Kodu paradigm:
- data/control generally flows from left to right, except in the case of parameters to functions, where it flows from right to left.

 I have another design where you click on the dice and select what upper bound you want, exactly as Jonny mentioned above. The team rejected that design!

**Comment by tballmsft** [comment]
replacing by https://github.com/microsoft/microcode/issues/207
