### ISSUE TITLE
micro:bit logo on home page is flat

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#182]
should it be aligned to the embossed style of microcode?  @clkantner  your call

<img width="366" alt="image" src="https://user-images.githubusercontent.com/4175913/192127445-d324526a-fc6a-4c5c-9c62-8b3a7c9b0b3a.png">

**Comment by tballmsft** [comment]
perhaps make it golden, like the logo in the press event?

**Comment by pelikhan** [comment]
Somewhat needs to fit in the splash screen

**Comment by pelikhan** [comment]
fixed by https://github.com/microsoft/microcode/commit/c570da9b0907f6b290aac4ab4088864c1734c7fb
