### ISSUE TITLE
rethinking the tiles in the Do section

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#207]
Do section is a bit of a mess
- radio send is a command receiving value from right
- random is a command sending value to right
- var assign is a command receiving value from the left.

Instead, propose the following
- The start of a Do section is value-consuming command, never a value-producing expression. 
- It is followed by a sequence of value-producing expressions, that flow to the left to as parameters to the command.

So
- random is an expression, not a command. 
- Variable assignment is a command. 
- We can use sum as the default to combine expressions. 
- An event  with associated numeric value that appears in When section can also appear as expression in Do section. So you can receive a value from radio, and use it in Do section. 

This will make everything consistent though we lose values flowing implicitly from left to right. Instead we explicitly mention them as parameter expressions that flow left to their command.

**Comment by pelikhan** [comment]
sounds good

**Comment by tballmsft** [comment]
- a function consumes everything to its right (add them together) up until another function
   - So, rnd 5 1 rnd 2 4 is (random 6) + (random 6)
   - no nesting (always linear)

- assignment to a variable

- default is sum everything

- Some constraints on functions that take an argument
   - Minus sign can't be followed by minus
   - random can't be followed by random

A sensor that is value producing and appears in the When section can be referred to as a value in the Do section
   - radio-receive
   - variable

The laws of addition

Dedicated filter for numbers (equality)

**Comment by eanders-ms** [comment]
Like human language, I think this language will have to sacrifice some formality for readability. I wouldn't want to see LEDs (a value producer) appearing before Paint (a value consumer), for example, because it reads opposite the way you'd describe it.

I agree it's a bit of a mess, especially around numbers. 

We might play with other kinds of indicators to make it plain which direction the data is flowing from a tile. Visually grouping parameters with their consumer might help, something like:
![image](https://user-images.githubusercontent.com/12176807/192589735-592133cc-2651-4c22-80df-b78111288a0f.png)

**Comment by tballmsft** [comment]
Eric, we are not going to reverse anything but variable assignment and random:
- variable assignment becomes an actuator at the beginning of Do
- random becomes a modifer

Paint and LEDs stay as they are.

Basically, we are giving up on values flowing implicitly from left-to-right. If you want a value from the left (When section) on the right side, you will need to put a tile.

Your group is a great idea since the rules above would allow

random 1 5 random 2 4

which is interpreted in lisp-like notation as:

(+ (random (+1 5)) (random (+ 2 4)))

**Comment by pelikhan** [comment]
@eanders-ms i got confused at first by the description as well.
