### ISSUE TITLE
navigation in the when picker should wrap to the next line

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#208]
This is an accessibility issue.

![image](https://user-images.githubusercontent.com/4175913/192604081-7a5c74d6-cbde-4c20-b3bf-404cb5ce04e1.png)

**Comment by tballmsft** [comment]
This is not simple, unfortunately.  Need to think on it for a bit.

**Comment by tballmsft** [comment]
https://github.com/microsoft/microcode/pull/213
