### ISSUE TITLE
art house keeping

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#210]
Here's a tentative list of art to delete. We've accumulated a bunch of dead art.

![image](https://user-images.githubusercontent.com/4175913/192620329-5aab2f4b-e2b0-4cd5-bbdf-39aaf70d4173.png)

**Comment by tballmsft** [comment]
I took care of most of this today. Will double check.

**Comment by tballmsft** [comment]
we need MISSING to show when we've made an error in mapping. The numbers are duplicated because they are currently used for LED ring.  The arrows are used by the hidden music editor. Everything else has been removed.

**Comment by pelikhan** [comment]
How are the number used in the led ring? We have color tile for the led.
________________________________

**Comment by pelikhan** [comment]
the leds are covered here 
![image](https://user-images.githubusercontent.com/4175913/192654464-bba95f36-9fff-48d6-aff0-acdfc7dae3cf.png)

**Comment by tballmsft** [comment]
I know, numbers are used both in filters and modifiers, that's why there appears to be duplicates.
