### ISSUE TITLE
please double size of exported program tiles

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#215]
They are super-small in the docs. Can you double there size when you generated them (1 pixel -> 2x2 region).

**Comment by pelikhan** [comment]
It's a small css tweak. 5rem minimum?

**Comment by pelikhan** [comment]
use 
![image](https://user-images.githubusercontent.com/4175913/192674770-0e8158d9-cccc-4322-aeed-d9e433a7b190.png)

**Comment by pelikhan** [comment]
add `{:class="icon"}` to icons
