### ISSUE TITLE
time/space efficiency (icon database)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#233]
Many of the icons have similar background but with a number/label on it. We can save flash (and RAM) by generating images on the fly from combinations of static images.

**Comment by pelikhan** [comment]
we'll save flash but not ram?

**Comment by tballmsft** [comment]
We can save RAM because instead of precomputing every image and storing it in the TID -> Image map. we can have a function that renders the image at a given offset in another image.

**Comment by tballmsft** [comment]
may slow things down too much though...
