### ISSUE TITLE
simple idea for rule with multiple actions

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#245]
What if we had an icon in modal for the sensor tile in the When section that would be something like "use the When section from the above rule".  That way we wouldn't have to duplicate code.  But there would be some UI issues.

**Comment by pelikhan** [comment]
let's duplicate away

**Comment by tballmsft** [comment]
agreed

**Comment by eanders-ms** [comment]
Agreed duplication isn't a bad thing here.
