### ISSUE TITLE
support for not having B button

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#258]
switch access boxes typically support 5 inputs, arrows + enter. Can we by keyboard navigatable without B?

**Comment by pelikhan** [comment]
One possible solution: interpret `Up` on top-most element as `back`

**Comment by tballmsft** [comment]
yes, that makes sense and is easy to do

**Comment by tballmsft** [comment]
https://github.com/microsoft/microcode/commit/210f99fccb953a168de9e9885503d4ee75850a63
