### ISSUE TITLE
Right arrow when on page icon

### ISSUE THREAD

**Issue by ramseyball** [microsoft/microcode#303]
Can advance to next page, with wrap around from page 5 to page 1.

**Comment by pelikhan** [comment]
right arrow needs to be able to scan the entire current page.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: ramseyball ***@***.***>
Sent: Thursday, October 13, 2022 8:54 AM
To: microsoft/microcode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/microcode] Right arrow when on page icon (Issue #303)


Can advance to next page, with wrap around from page 5 to page 1.
