### ISSUE TITLE
Consider rename to MicroKode

### ISSUE THREAD

**Issue by ramseyball** [microsoft/microcode#306]
Pros

- Gives nod to Kodu heritage
- Also avoids conflict with well used term microcode 

any cons?

**Comment by pelikhan** [comment]
No, let's go for it. We probably need to be careful about redirects, i don't think gh pages keep the old page so we might need to create a new repo.

Need updated art for landing page.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: ramseyball ***@***.***>
Sent: Friday, October 14, 2022 1:56 PM
To: microsoft/microcode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/microcode] Consider rename to MicroKode (Issue #306)


Pros

  *   Gives nod to Kodu heritage
  *   Also avoids conflict with well used term microcode

any cons?

**Comment by pelikhan** [comment]
We're going to break a lot of links; it's going to be tedious. I think "microcode for micro:bit" is fine.
