### ISSUE TITLE
Repo one-liner confusing

### ISSUE THREAD

**Issue by ramseyball** [microsoft/microcode#307]
Physical computing for young and variable coders on the micro:bit V2 (beta).

“Variable”??

**Comment by pelikhan** [comment]
Reference: http://setonmontessori.org/institute/site/wp-content/uploads/2016/11/variability-Seton.pdf

**Comment by pelikhan** [comment]
Change it as you wish
________________________________

**Comment by ramseyball** [comment]
Seems fine to me, upon reading the reference. But we use disability later in README so should be consistent.

**Comment by ramseyball** [comment]
And, of course, we use the word variable later for another purpose.

**Comment by pelikhan** [comment]
Feel free to update as needed.
________________________________

**Comment by ramseyball** [comment]
I can’t update the repo info.
