### ISSUE TITLE
melody field editor ready for code gen

### ISSUE THREAD

**Issue by ramseyball** [microsoft/microcode#325]
the 8 notes of a melody tile are encoding as a string, where each character has one of 9 possible values:

- "." means no note plays (rest)
- "7" is C 
- "6" is D (whole note above C) 
- "5" is E 
- down to "0", which is the C one octave above the initial C ("7")

In the image below, you can see a sequence of three melody tiles. The first one is encoded by the string "76543210", so does the major scale going up from C to octave above. in the second tile, each note is repeated, going down step by step("00112233".) In the third tile, we skip some notes ("44..6677")

![image](https://user-images.githubusercontent.com/2252454/196956627-3f25bd75-ddd0-47ea-925e-e18047847aaa.png)

**Comment by pelikhan** [comment]
I've hidden this block under `options.melody` until the codegen is in place.

**Comment by ramseyball** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
