### ISSUE TITLE
Mélody editor needs sound preview

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#340]
typically play melody in a loop and have a visual "cursor"

Just sounding the current note would be good.

**Comment by tballmsft** [comment]
agreed, by sending note (or note sequence) to micro:bit?

**Comment by pelikhan** [comment]
Maybe send the entire sequence every time the user changes a note, or send a single note.

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/197831933-f55241f4-1d3e-45c1-a8a9-4ce3de62a07b.png)
