### ISSUE TITLE
artwork generation fails when rule is too wide

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#364]
The sixth rule in the clap program now overflows the screen width (when the plus sign is added).  This results in a very bad image.  Image after plus sign added is a very thin column (do the artwork build yourself to see). Image before "+" sign added:

![image](https://user-images.githubusercontent.com/10767146/203164151-03a2cb89-8621-40e3-939c-ea60700f01f9.png)

**Comment by pelikhan** [comment]
You need to update the math that estimate the screen width to account for pluses.

**Comment by tballmsft** [comment]
got it - thanks - I thought that code would be generic over the EditorButtons.
