### ISSUE TITLE
code gen is broken

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#367]
Various built-in samples no longer working on HW (programs sent from web browser):
- hamster
- rock paper scissors
- coin flip
- chuck a duck

Failure mode is that the micro:bit hangs and a single LED (usually in upper left quadrant) turns on. Persists whenever program is compiled (fortunately, can switch to samples and hit new program in time before compile takes place).

**Comment by tballmsft** [comment]
Works fine with simulator.

**Comment by pelikhan** [comment]
Let's rollback to a version that worked.

**Comment by tballmsft** [comment]
yes, please. how do we do that?

**Comment by tballmsft** [comment]
I don't think this is ch

**Comment by mmoskal** [comment]
is there something for me to do here?
