### ISSUE TITLE
button mapping is buggy

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#374]
I find that when a kittenbot button is attached and the micro:bit reset that the mapping of buttons on the micro:bit to integer ranges gets messed up. The micro:bit (fixed) buttons (A,B,logo,pins0,1,2) don't always get mapped to 0..5 when a button module is already attached to the Jacdac bus on reset. Instead, I find that the button module might have a value 0 (rather than 6), and so act as the A button. 

Note that the problem doesn't occur if we start with nothing connected to the Jacdac bus and then add the module. The problem only occurs when the button is connected to the micro:bit and it is reset.

**Comment by tballmsft** [comment]
i see
```
void app_init_services() {
    jd_role_manager_init();
    init_jacscript_manager();
    init_local_services();

    // tsagg_init(&noop_cloud);
}
```
so if external buttons are already connected, perhaps this explains things. we need to give priority to the built-in buttons

**Comment by mmoskal** [comment]
Generally, the program should only start 1.5s after boot, see https://github.com/microsoft/jacdac-c/blob/codal-jacdac/jacscript/jacscriptmgr.c#L365 - this should be enough time for devices to enumerate. I'll try to locate my micro:bit and look at this tomorrow.

**Comment by pelikhan** [comment]
Can we get some screen animation during those 1.5s of restart time?

**Comment by tballmsft** [comment]
To be clear, the problem I am seeing is that when external buttons are plugged in, they seem to get the roles that are usually allocated to the built-in buttons, yielding bad user experience.

**Comment by mmoskal** [comment]
Can't repro. My [testcase](https://microsoft.github.io/microcode/#H4sIAB7UrmMAA4WQyw6CMBBFfwnUaLrEQnSqxWiLojsVTQZQSdAgfL1j64OVLiY309z2nPRQi2p/YufNaHmCtBhA7uEsv1LCKyVliVEDGKsK5wr6q1oMQyWSKRcjurODbN1A7pSQOaardeBOfK+SmsYPbGrvLn0aTbs9KwCrb/f3FJC7bDomj9rwtUTDH1p+4Fr+2vAXaWRctXUNpY4uLZenR9vN7ipDes92//nwDOPYKQ9dNzmq++evjsuXIxK3e2WmUwv1dHx3TYeLziYWzXbFbpBeMEnhFvJeI7lgDx0n6ByQAQAA)

**Comment by tballmsft** [comment]
Hmm... yeah, I can't repro anymore either.
