### ISSUE TITLE
two KeycapButton can't work until replug 

### ISSUE THREAD

**Issue by smfox10** [microsoft/microcode#378]
![image](https://user-images.githubusercontent.com/3880290/211231106-cb18bb3d-0fbb-49d9-af77-aeef5359fd36.png)

1、I made a program about two KeycapButton test
2、The module was plugged in ahead of time
3、When I rest the microbit, the physical result is not consistent with the code
4、When I replug two KeycapButton，it works fine

https://user-images.githubusercontent.com/3880290/211231318-df2bb61e-2d21-48c9-ae55-788ed611f908.mp4

**Comment by tballmsft** [comment]
@smfox10: I can't repro. Can you provide a more detailed list of steps (from a new program) that causes the error? Thanks!

**Comment by smfox10** [comment]
I tried again and it works.Thx~
