### ISSUE TITLE
two sample crash in MicrobitV2

### ISSUE THREAD

**Issue by smfox10** [microsoft/microcode#388]
My MicrobitV2 version is V2.00.
The firmware is V2.4.37

These two sample programs will crash
![image](https://user-images.githubusercontent.com/3880290/236615753-512732ef-f3c1-4252-9507-92692a7f1002.png)

https://user-images.githubusercontent.com/3880290/236615821-3ee8788d-154c-43e7-9800-048a9893fad7.mp4

**Comment by tballmsft** [comment]
OK. I will look into this.

**Comment by tballmsft** [comment]
Note that after the crash, if you restart and edit the program, in the case of the reaction time sample, everything works.

**Comment by smfox10** [comment]
I try again,same problem,Maybe  MicroCode cn-firmware problem?
![image](https://github.com/microsoft/microcode/assets/3880290/7a73a614-5ae3-43e0-84b6-e1694d75d9cf)

**Comment by smfox10** [comment]
> 

I followed your steps and it worked. I expect to be able to open and run directly

**Comment by tballmsft** [comment]
of course. I am working on a fix, but it requires quite a bit of refactoring, so will take me some time.

**Comment by pelikhan** [comment]
Well we removed the built in samples... so this is fixed.
