### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by mrcodycreed** [microsoft/microcode#390]
I was surprised to find that microbit displays like “newbit” allow microcode onboard coding. I ran rock paper scissors but something went wrong and my display broke. It won’t use the direction buttons as inputs now. I will do further experiments.

**Comment by pelikhan** [comment]
what is a "newbit"?

**Comment by mrcodycreed** [comment]
> what is a "newbit"?

Newbit uses V2 to create Makecode arcade video games to run on a display with buttons.

microcode displays and runs on the display and the irks with the buttons.

**Comment by mrcodycreed** [comment]
> what is a "newbit"?

https://www.kittenbot.cc/products/newbit-arcade-shield

**Comment by tballmsft** [comment]
The idea of MicroCode is that you can use the new:bit Arcade Shield to program the microbit itself. There is no support for programming against the direction pad and buttons on the shield. The goal is that when you unplug the micro:bit from the shield, the MicroCode program runs fine against the micro:bit features.
