### ISSUE TITLE
loading old format program crashes

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#422]
when trying to edit a program that was formerly written using JSON representation, the editor crashes.

- launch dev server
- go to release microcode, open editor
- edit URL (keep the hash to load the project) to point to local server running new serialization format
crash

**Comment by tballmsft** [comment]
my thought is to move off of the old format and not support it at all going forward.

**Comment by pelikhan** [comment]
Anyone who shared a URL with microcode will have it broken.😞 oh well.

**Comment by ramseyball** [comment]
i can support both in web app, but not HW

**Comment by pelikhan** [comment]
It’s fine let’s move on
________________________________
