### ISSUE TITLE
samples that have [Open in MicroCode] are outdated

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#426]
A number of samples have a URL in the old format. Search for `[Open in MicroCode]`

It also looks like the render art features not get the full list of samples anymore; only the rawsamples, not the web ones.

**Comment by tballmsft** [comment]
did you fix this?

**Comment by pelikhan** [comment]
I’ve fixed the generation of url but need to patch sample markdown files
________________________________

**Comment by tballmsft** [comment]
I will do this

**Comment by pelikhan** [comment]
done
