### ISSUE TITLE
loading save slots crashes on hardware

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#427]
- try to load a program from any slot
- 999 error

**Comment by pelikhan** [comment]
The save slot are containing programs with the old format; we should swallow deserialization issues.

**Comment by tballmsft** [comment]
this is not a huge issue. people will start with fresh hex files, for the most part. I don't really think it is worth keeping the old JSON format alive, do you?

**Comment by tballmsft** [comment]
https://github.com/microsoft/microcode/commit/0bc0fefd4aae37a5a7d47604db48f6743c07fe80
