### ISSUE TITLE
web site at https://microsoft.github.io/microcode-docs/

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#44]
We need more than just the MicroCode app at https://microsoft.github.io/microcode/

We need to have:
- tutorial (how to create programs)
- sample programs, that could be loaded into the MicroCode app

For an example, see https://microsoft.github.io/tilecode/

Additionally, the MicroCode app has hooks for accessibility, which would be great to make use of.

**Comment by tballmsft** [comment]
We have spun up a new repo to host the web site: https://github.com/microsoft/microcode-docs. It will have a simple structure of three iframes, hosting:

- the arcade simulator running MicroCode app (this repo)
- a help frame (which will dynamically update as user makes selections in the MicroCode app
- the Jacdac dashboard, running the micro:bit simulator

**Comment by oldukhno** [comment]
Some clarification needed.

> 
> * the arcade simulator running MicroCode app (this repo)
> * a help frame (which will dynamically update as user makes selections in the MicroCode app
Did you mean to update the frame with the metadata/info which we get from the MicroCode app?
> * the Jacdac dashboard, running the micro:bit simulator
To make it actionable by external contributors like me, we need here more details including some links and screenshots if possible. So far, I found just [this ](https://microsoft.github.io/jacdac-docs/dashboard/) but I'm not sure if this is the thing you meant here.

**Comment by tballmsft** [comment]
> * the arcade simulator running MicroCode app (this repo)

this is https://microsoft.github.io/microcode/, built from this repo

> * a help frame (which will dynamically update as user makes selections in the MicroCode app
>   **Did you mean to update the frame with the metadata/info which we get from the MicroCode app?**

Yes.  this frame would get a tile ID from the MicroCode app, look up some associated markdown, and display it.

> * the Jacdac dashboard, running the micro:bit simulator

See the instructions in the README for this repo, which show how the Jacdac dashboard and a second website (the MicroCode app) can be combined together

* https://microsoft.github.io/jacdac-docs/clients/javascript/devtools?jacscript=1#http://127.0.0.1:7000

>   **To make it actionable by external contributors like me, we need here more details including some links and screenshots if possible. So far, I found just [this ](https://microsoft.github.io/jacdac-docs/dashboard/) but I'm not sure if this is the thing you meant here.**

**Comment by pelikhan** [comment]
We decided to host the docs in microcode itself.
