### ISSUE TITLE
send 2 events for wall / line det3ector?

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#456]
@tballmsft can the robot send 2 radio messages for events? is it going to be an issue with the interpreter?

**Comment by tballmsft** [comment]
Don't know - try it out - depends on what Michal does in the runtime.

**Comment by pelikhan** [comment]
@mmoskal question for you

**Comment by mmoskal** [comment]
At the Jacdac level it works - two Jacdac packets will be generated. Now, the code for the rule will be triggered twice in quick succession, so you need to make sure there is no race there. In particular you should not be doing async stuff in role dispatcher.

**Comment by pelikhan** [comment]
I am thinking about reception, what happens when you trigger twice a rule, do you cancel one?
________________________________

**Comment by mmoskal** [comment]
Rule bodies are emitted as separate procedures. They are invoked with BG_MAX1 meaning if the procedure is already running it is not started again. So the second packet would be ignored.
