### ISSUE TITLE
move tids as strings to web app (and doc) only

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#491]
will be nice to get rid of these strings in the hex file and replace if-then-else on strings with switch on numbers. https://github.com/microsoft/microcode/pull/492

**Comment by pelikhan** [comment]
4kb flash size on each conversion function i think

**Comment by tballmsft** [comment]
switch statement on number should be more compact.

**Comment by tballmsft** [comment]
need to redo tooltip mapping as well
