### ISSUE TITLE
Jacdac KeycapButton conflicts with Microbit A&B

### ISSUE THREAD

**Issue by smfox10** [microsoft/microcode#493]
Previous use was OK, recent use has been problematic, see video demonstration.

When I don't have the KeycapButton plugged in, the programming logic for keys A & B works fine.
Once plugged in, the programming logic is not normal.

https://github.com/microsoft/microcode/assets/3880290/34e5dc5d-18fb-4ad7-a65e-1ce3628dfe6c

**Comment by smfox10** [comment]
The firmware version I'm using is v2.5.16

**Comment by ramseyball** [comment]
I will check tomorrow.

**Comment by ramseyball** [comment]
I tried same program with 2.5.18 and was not able to repro.

**Comment by smfox10** [comment]
I had test 2.5.18. Same bug

https://github.com/microsoft/microcode/assets/3880290/b1d1101e-a03c-4ac6-8682-78c53ca46160

**Comment by tballmsft** [comment]
Wow, I did the exact same setup and was not able to reproduce...
