### ISSUE TITLE
Suggestion: add a gesture - face-up

### ISSUE THREAD

**Issue by smfox10** [microsoft/microcode#499]
Due to the addition of the mechanical claw, I use the AB button for opening and closing. The direction of the cart is controlled by attitude detection. Now make the robot stop, by touching the logo. This approach will keep my hands busy.

I would like to add a gesture detection - face up - so that I can easily control the robot to stop.

![image](https://github.com/microsoft/microcode/assets/3880290/0f7e82c1-7ebf-4dbb-9fe5-b33d13e0f83d)

**Comment by pelikhan** [comment]
And face down

**Comment by pelikhan** [comment]
@smfox10 try the microphone to stop!

**Comment by tballmsft** [comment]
Done: https://github.com/microsoft/microcode/pull/500
