### ISSUE TITLE
MicroCode live-tutorial

### ISSUE THREAD

**Issue by oldukhno** [microsoft/microcode#53]
User should be able to hover mouse over an element in the editor and get instant tip on how to proceed further.

The tip may include:
- Information about the current element
- Further reasonable actions

Accessibility: the tip should support screen reader

The editor and game containers on the emulator (see [pxt]) are rendered on html canvas, so we cannot really get a metadata about hovered elements. We need to explore a way to customize pxt emulator and propagate metadata about the elements to html elements or any other way (localstorage, uri), so we can read that in the web-app and represent as a tip.

**Comment by pelikhan** [comment]
Mouse support is a stretch as it would require to modify makecode significantly.

However we have a cursor in microcode so the JavaScript could be notified whenever the cursor is moved and update documentation based on that position. This is also related to the screen reader.

@tballmsft where is the relevant code that updates the cursor? We are going to need a stable id for each tile that we will allow us to pull the relevant docs.

**Comment by tballmsft** [comment]
Whenever the cursor moves, the following function is called in editor.ts

> line          private moveTo(target: Button) {

**Comment by pelikhan** [comment]
Note that we should differentiate contextual help and step-by-step tutorials. Having context help should definitely be doable in the web app; once the editor starts sending us "what is the current context"

**Comment by tballmsft** [comment]
@pelikhan - there is a lot more that the editor could do then just give the name of the current tile. I guess my question is how to define "context".

**Comment by tballmsft** [comment]
We know the following:
- what tile in the editor we are on (is it a program tile or editor feature)
- does the tile support a pop-up menu?
- what is the rule (if any) the cursor is on?
- what page are we on?

**Comment by tballmsft** [comment]
We are going to have a separate repo for the web site and define a simple iframe message interface to communicate between MicroCode app and the help section: https://github.com/microsoft/microcode-docs

**Comment by pelikhan** [comment]
we can keep docs in microcode folder if we limit ourselfves to markdown + jenkins. might be easier.
