### ISSUE TITLE
artwork for sound emojis

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#55]
Micro:bit can play 10 sound emoji. We need graphics for the 10 emoji (see assets.ts), which currently just point to existing images:

```
            this.reg[TID_MODIFIER_EMOJI_GIGGLE] = icondb.tile_page_1
            this.reg[TID_MODIFIER_EMOJI_HAPPY] = icondb.tile_page_2
            this.reg[TID_MODIFIER_EMOJI_HELLO] = icondb.tile_page_3
            this.reg[TID_MODIFIER_EMOJI_MYSTERIOUS] = icondb.tile_page_4
            this.reg[TID_MODIFIER_EMOJI_SAD] = icondb.tile_page_5
            this.reg[TID_MODIFIER_EMOJI_SLIDE] = icondb.tile_value_1
            this.reg[TID_MODIFIER_EMOJI_SOARING] = icondb.tile_value_2
            this.reg[TID_MODIFIER_EMOJI_SPRING] = icondb.tile_value_3
            this.reg[TID_MODIFIER_EMOJI_TWINKLE] = icondb.tile_value_4
            this.reg[TID_MODIFIER_EMOJI_YAWN] = icondb.tile_value_5
```

**Comment by clkantner** [comment]
Where can I find the existing images to reference? And how do users access these in the microcode interface? Lastly, is there somewhere I can hear what they sound like?

**Comment by tballmsft** [comment]
@clkantner  - try this MakeCode program to play with the sounds: https://makecode.microbit.org/_Yy9WcA8j0hFf

There don't appear to be any artwork associated, but maybe ask Richard. 

You should build locally to see the user interface with latest mods. Click on the speaker icon to get the list of options (currently, reusing other images, no emojis, as mentioned above.  Please see instructions at https://github.com/microcode/makecode  on how to build locally.  Let me know if you have any questions.

**Comment by clkantner** [comment]
Sorry I think I might need some help to build it... I have VS code installed, and Eric showed me how to go to localhost but it's an error right now... "can't reach page" when I go to http://127.0.0.1:7001/ . Also I don't understand the instructions, what does "mkc serve" do? When I ran it, it said it doesn't exist? "command not found: mkc" Sorry I don't really know what to do, or would it be okay to make the pixel art separately in my own program and add it in later? Or maybe I can go into the office later this week if you or Eric are there!! Thank you for your patience.

<img width="467" alt="Screen Shot 2022-09-13 at 10 43 25 AM" src="https://user-images.githubusercontent.com/106267801/189973483-4285ae89-1d5c-420b-aab0-4765cce140f3.png">

<img width="543" alt="Screen Shot 2022-09-13 at 10 45 10 AM" src="https://user-images.githubusercontent.com/106267801/189973577-7d13a797-1f3c-4e89-91ad-78ea8bc84838.png">

**Comment by eanders-ms** [comment]
Try `npx mkc serve`. npx is smarter about finding node-installed utils.

**Comment by clkantner** [comment]
Thank you so much, now I can go to http://[127.0.0.1:7001](http://127.0.0.1:7001/)/ and I see the simulator. But it's showing me the older version I think... is there a way to get the newest version in here? Do I download it? But then will it overwrite my changes?

**Comment by eanders-ms** [comment]
`git pull` in the folder will grab latest source. mkc should be able to rebuild it on the fly, if it's running.

**Comment by tballmsft** [comment]
@clkantner - one more thing regarding artwork. I do the following:

- create 16 x 16 artwork using arcade.makecode.com
- copy the code from the JavaScript view
- paste into assets.ts
- make sure it works locally
- git commit and push

**Comment by pelikhan** [comment]
Can we add these instructions to README.md?

**Comment by tballmsft** [comment]
will do.
