### ISSUE TITLE
artwork for accelerometer events...

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#57]
Here is what micro:bit has... I will add plumbing to code (we won't do the 3g, 6g, 8g for now):

![image](https://user-images.githubusercontent.com/10767146/189982034-a444e736-d46d-41f0-880c-a88f770cd3a0.png)

**Comment by clkantner** [comment]
Just noting for myslef, the 6 icons we need are
- Shake
- Free fall
- Tilt up
- Tilt down
- Tilt left
- Tilt right
