### ISSUE TITLE
quiet microphone event

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#58]
quiet event is not useful in practice -- at least in a noisy classroom you will have a lot of transitions from "some noise" -> "no noise", so it triggers all the time.

If we keep quiet, we need to least require something like 2 seconds with low noise threshold.

**Comment by tballmsft** [comment]
I'd like to keep quiet event for now. @mmoskal  - ideas on the 2 second check?

**Comment by mmoskal** [comment]
we can do 2 seconds

**Comment by pelikhan** [comment]
i think this is done, @mmoskal ?

**Comment by mmoskal** [comment]
there's no threshold right now
