### ISSUE TITLE
should A/B buttons resemble micro:bit?

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#66]
Following up on discussion. Feel free to discuss more.  My suggestion is that we should strive for consistency in our visual language. In this case, I think the question is about how to represent micro:bit components in our UI.  In the case of the press-event, we have A, B, micro:bit logo, and three pins that can all function as "buttons" that can receive a press-event.

**Comment by Lorrainbow** [comment]
We fell for this one. The button icon looks like the B button on the kittenbot arcade shield (red). So we were pressing this button assuming that's what we had coded. When it's actually the micro:bit button (and needs a 2nd tile with the button name)

**Comment by clkantner** [comment]
I initially thought our buttons were going to be the kittenbot shield, but once I tried pressing it, it didn't work. So I agree now it's a bit confusing. We could have the buttons both be green instead...

**Comment by eanders-ms** [comment]
Playtested with my kids today, first time. They got stuck on this and I had to explain it. It's challenging that the A/B graphics on the microbit are so tiny. Still, I think we should try.

![thumbnail_IMG_7790](https://user-images.githubusercontent.com/12176807/191899156-6acd3296-8642-4897-9e81-93c46fafa0d2.jpg)

Consider something like

![image](https://user-images.githubusercontent.com/12176807/191899644-cb9c9416-7a2d-4a58-ab86-fdcc2d11a787.png)

**Comment by eanders-ms** [comment]
Reopening for reconsideration.

**Comment by pelikhan** [comment]
or something like 
![image](https://user-images.githubusercontent.com/4175913/191901118-0e1e2c39-4100-4e7a-ab8a-e9519385373a.png)

**Comment by pelikhan** [comment]
Let's try the triangles, it's the signature design of the bit

**Comment by clkantner** [comment]
<img width="336" alt="Screen Shot 2022-09-23 at 9 19 24 AM" src="https://user-images.githubusercontent.com/106267801/192006789-fd7e5ea2-c212-46e6-b597-1fb82cb424a0.png">

Let's try this!
