### ISSUE TITLE
backspace key currently restarts simulator

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#68]
@eanders-ms. Can you please use the MakeyMakey stuff to remap the following keys to controller.B?

- Enter
- ESC
- Backspace

**Comment by pelikhan** [comment]
We can keymap.setPlayerKeys, keymap.setSystemKeys to remap keys. We can also reuse player 2 keys to get more shortcuts.

**Comment by pelikhan** [comment]
We really need to fix this one. The enter to go back is hella confusing. I don't see keymap in game---light right now.

**Comment by pelikhan** [comment]
found those https://github.com/microsoft/pxt-common-packages/blob/23948f960545a73a9584be0c672543a4306d377c/libs/game/keymap.ts#L26
