### ISSUE TITLE
Trying to add 4 lines of code crashes the screen

### ISSUE THREAD

**Issue by Lorrainbow** [microsoft/microcode#91]
Steps:
1. Create 3 lines of valid code
2. Create a 4th line of valid code
3. In the DO section of the 4th line of code press the + icon

Result: The screen goes white  (We recommend a blue screen of death :) )
You have to restart the shield in order to get back to the code screen. 

This has been replicated several times. 

Firmware: v1.0.17
Newbit Arcade Shield v1.0

**Comment by tballmsft** [comment]
Hmm... I am not able to reproduce...

**Comment by pelikhan** [comment]
Probably outdated by now.
